version: '2'
services:
    web:
        build:
            context: ./
            dockerfile: docker/web.docker
        volumes:
            - ./:/var/www
        ports:
            - "8086:80"
        links:
            - app
    app:
        build:
            context: ./
            dockerfile: docker/app.docker
        volumes:
            - ./:/var/www
        links:
            - mysql-server
        environment:
            - "DB_PORT=3306"
            - "DB_HOST=mysql-server"

    mysql-server:
      image: mysql:5.6
      environment:
        - "MYSQL_ROOT_PASSWORD=secret"
        - "MYSQL_DATABASE=dockerApp"
        - "MYSQL_ROOT_HOST=172.24.0.1"
      ports:
        - 3309:3306

    memcached:
        image: memcached
        ports:
          - 11233:11211